### ISSUE TITLE
Browser detection does not work on Grails 2.0

### ISSUE THREAD

**Issue by goedef** [henadzit/grails-browser-detection#1]
I upgraded from browser detection plugin 0.3.1 to 0.3.3 and I encoutered null pointer exceptions while using the <g tag.

**Comment by henadzit** [comment]
Hi, 

Could you please provide a stack trace?

Thanks

**Comment by goedef** [comment]
Hi,

It works perfectly in grails 1.3.7, but when I upgraded (and later also 
on a fresh grails 2.0.1 install) it returnes a nullpointer exeption.

The stacktrace on the following tag :

browser:isMobile${response.sendRedirect(request.contextPath+"/mobile")}/browser:isMobile

is:

Normal browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:11.0) Gecko/20100101 
Firefox/11.0
| Error 2012-03-26 17:12:08,090 [http-bio-8080-exec-5] ERROR 
errors.GrailsExceptionResolver  - NullPointerException occurred when 
processing request: [GET] /20test/test/index
Cannot invoke method empty() on null object. Stacktrace follows:
Message: Error processing GroovyPageView: Error executing tag 
browser:isMobile: Cannot invoke method empty() on null object
    Line | Method
->>   2 | runTask in /grails-app/views/test/index.gsp

---

Caused by GrailsTagException: Error executing tag browser:isMobile: 
Cannot invoke method empty() on null object
->>  14 | doCall  in /grails-app/views/test/index.gsp

---

Caused by NullPointerException: Cannot invoke method empty() on null object
->> 221 | handle  in org.geeks.browserdetection.BrowserTagLib

---

|    41 | doCall  in org.geeks.browserdetection.BrowserTagLib$_closure1
|    14 | doCall  in 
Users_fdgoede_IdeaProjects_20test_grails_app_views_test_index_gsp$_run_closure2
|    17 | run     in 
Users_fdgoede_IdeaProjects_20test_grails_app_views_test_index_gsp
|   886 | runTask in java.util.concurrent.ThreadPoolExecutor$Worker
|   908 | run     in     ''
^   680 | run . . in java.lang.Thread

Op 23-03-12 08:49, Gennady Tsarik / Henadzi Tsaryk / vare6gin schreef:

**Comment by goedef** [comment]
This workaround seems to work for me.

class MyTagTagLib {

```
def userAgentIdentService

def browserIsMobile = { body->
    if (userAgentIdentService.isMobile())
        out << body

}
```

}

And:
<g:browserIsMobile>${response.sendRedirect(resource(dir:'/mobile', file:'').toString())}/g:browserIsMobile

**Comment by henadzit** [comment]
Thank you for feedback!
I will fix it soon.

**Comment by henadzit** [comment]
Hi,

The issue is resolved. Please, check out release 0.4.

**Comment by goedef** [comment]
Hi Gennady,

I did install the plugin and it works again like a charm!
Thanks for the help and the update.

What was the issue?

Best regards,
Fred

Op 02-04-12 00:23, Gennady Tsarik / Henadzi Tsaryk / vare6gin schreef:

**Comment by henadzit** [comment]
Seems like, Grails developers changed behavior of pageScope in version 2.0. Some variables were stored in the page scope by the plugin. 
Version 1.3.7: if a nonexistent value is requested, an exception is thrown.
Version 2.0: currently it works like the request scope or session scope, so null value is returned in this case. 
I replaced the page scope with the request scope for making the plugin working for all Grails versions.

**Comment by henadzit** [comment]
Thanks for feedback!
