### ISSUE TITLE
Non-serializable attribute org.geeks.browserdetection.UserAgentIdentService_agentInfo

### ISSUE THREAD

**Issue by sarbogast** [henadzit/grails-browser-detection#2]
When I run my Grails 2.0.3 app using version 0.4 of your plugin, I get the following Grails runtime exception:

Class
java.lang.IllegalArgumentException
Message
setAttribute: Non-serializable attribute org.geeks.browserdetection.UserAgentIdentService_agentInfo
Trace
   Line | Method
->>  82 | getUserAgent in org.geeks.browserdetection.UserAgentIdentService

---

|   120 | isBrowser    in     ''
|    95 | isFirefox .  in     ''
|    79 | show         in net.groupwall.WallController
|    35 | invoke . . . in net.stax.appserver.webapp.RequestMonitorValve
|    49 | invoke       in net.stax.appserver.admin.StaxApplicationQueryValve
|    31 | invoke . . . in net.stax.appserver.webapp.RequestSetupValve
^   662 | run          in java.lang.Thread

Any idea what this is?

**Comment by sarbogast** [comment]
I just investigated and I noticed that nl.bitwalker.useragentutils.UserAgent (which seems to be the class of what you are trying to store in the session) is not Serializable in version 1.5 of UserAgentUtils. But it is in version 1.6. Any change you can upgrade to the latest version of UserAgentUtils anytime soon?

**Comment by sarbogast** [comment]
Apparently, someone else had a similar issue: http://java.net/jira/browse/USER_AGENT_UTILS-18

**Comment by henadzit** [comment]
Hi,

Thank you for feedback! 

I upgraded the UserAgentUtils library.
Now I am waiting for grails developers approval. Seems like, my credentials are invalid right now on the grails plugins repo.

Thanks

**Comment by sarbogast** [comment]
Any news on the release front? Because for now I'm using your plugin via inline compilation and I would really like to close this. Thanks for the quick reaction by the way.

**Comment by henadzit** [comment]
I couldn't release the new version even after emailing grails developers. Sorry, I am very busy now. You can try to follow the guide (http://grails.org/Creating+Plugins) for releasing the new version.

I will try later but I will really appreciate if you try too.

Thanks

**Comment by sarbogast** [comment]
I managed to release the plugin but I've had to change BuildConfig.groovy and application.properties slightly to make it work. I don't understand every change I made, I simply copied some working stuff over from one of my own plugins:

in BuildConfig.groovy:

``` groovy
    plugins {
        build(":tomcat:$grailsVersion",
                ":release:2.0.0",
                ":rest-client-builder:1.0.2") {
            export = false
        }
    }
```

And in application.properties I removed all plugin versions

**Comment by henadzit** [comment]
Hi, thank you very much!

Seems like your change made the plugin not compatible with grails versions older than 2.0. At least version 0.4 isn't in the output of "grails list-plugins" on 1.3.7. I will try to take a look at it later.

Anyway, thank you much!
